using System.Collections.Generic;

namespace OCanada
{
    public static class Notes
    {
        public static readonly Dictionary<string, float> NotePitches = new Dictionary<string, float>()
        {
            {"a#5", 932.328f},
            {"a5", 880.000f},
            {"b5", 987.767f},
            {"c6", 1046.502f},
            {"d#5", 622.254f},
            {"d#6", 1244.508f},
            {"d5", 587.330f},
            {"d6", 1174.659f},
            {"f5", 698.456f},
            {"g#5", 830.609f},
            {"g5", 783.991f},
        };
        
        public static readonly string[] OCanadaNotes =
        {
            "g5",
            "a#5",
            "a#5",
            "d#5",
            "f5",
            "g5",
            "g#5",
            "a#5",
            "c6",
            "f5",
            "g5",
            "a5",
            "a5",
            "a#5",
            "c6",
            "d6",
            "d6",
            "c6",
            "c6",
            "a#5",
            "f5",
            "g5",
            "g#5",
            "g5",
            "f5",
            "g5",
            "g#5",
            "a#5",
            "g#5",
            "g5",
            "g#5",
            "a#5",
            "c6",
            "a#5",
            "g#5",
            "g5",
            "f5",
            "f5",
            "g5",
            "g#5",
            "g5",
            "f5",
            "g5",
            "g#5",
            "a#5",
            "g#5",
            "g5",
            "g5",
            "f5",
            "a#5",
            "a#5",
            "a5",
            "g5",
            "a5",
            "a#5",
            "g5",
            "a#5",
            "a#5",
            "d#5",
            "g#5",
            "c6",
            "c6",
            "f5",
            "a#5",
            "b5",
            "b5",
            "c6",
            "g#5",
            "g5",
            "f5",
            "d#5",
            "f5",
            "g5",
            "a#5",
            "d#6",
            "d#6",
            "c6",
            "g#5",
            "g5",
            "f5",
            "a#5",
            "d5",
            "d#5",
        };
    }
}